version: '3'

services:
  web:
    build: .
    command: gunicorn a_core.asgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - media_file:/app/media
      - static_files:/app/staticfiles
    depends_on:
      - db
      - redis


  db:
    image: postgres:16
    env_file:
      - .db.env

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - media_file:/app/media
      - static_files:/app/staticfiles
    depends_on:
      - web

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped

volumes:
  media_file:
  static_files:
