version: '3'

services:
  django_wsgi:
    container_name: django_wsgi
    build: .
    command: uwsgi --socket=:9000 --module=a_core.wsgi:application --py-autoreload=1
    volumes:
      - .:/code

  django_asgi:
    container_name: django_asgi
    build: .
    command: daphne -b 0.0.0.0 -p 8000 a_core.asgi:application
    volumes:
      - .:/code

  db:
    image: postgres:16
    env_file:
      - .db.env

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - media_file:/app/media
      - static_files:/app/staticfiles
    depends_on:
      - django_wsgi
      - django_asgi

  redis:
    image: redis:latest

volumes:
  media_file:
  static_files:
